# Generated by Django 4.1.2 on 2022-11-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CITAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=30)),
                ('paciente', models.CharField(max_length=50)),
                ('medico', models.CharField(max_length=50)),
                ('fechacitacion', models.DateField(verbose_name='%Y-%m-%d %H:%M:')),
            ],
        ),
        migrations.CreateModel(
            name='MEDICOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PACIENTE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('fono', models.CharField(max_length=15)),
            ],
        ),
    ]
