# Generated by Django 4.1.2 on 2022-11-19 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APLICACION', '0002_alter_citas_fechacitacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citas',
            old_name='fechacitacion',
            new_name='fecha',
        ),
    ]
