# Generated by Django 4.1.2 on 2022-11-19 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APLICACION', '0003_rename_fechacitacion_citas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APLICACION.medicos'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APLICACION.paciente'),
        ),
    ]
