# Generated by Django 4.1.2 on 2022-11-25 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APLICACION', '0004_alter_citas_medico_alter_citas_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_f', models.CharField(max_length=45)),
                ('nombre_cli', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('fono', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_f', models.CharField(max_length=45)),
                ('nombre_fun', models.CharField(max_length=45)),
                ('especialidad', models.CharField(max_length=45)),
                ('user', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_masc', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_at',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atencion_at', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_m',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atencion_m', models.CharField(max_length=45)),
            ],
        ),
        migrations.DeleteModel(
            name='CITAS',
        ),
        migrations.DeleteModel(
            name='MEDICOS',
        ),
        migrations.DeleteModel(
            name='PACIENTE',
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APLICACION.raza'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APLICACION.tipo_m'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='nom_mas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APLICACION.mascota'),
        ),
        migrations.AddField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elclientexd', to='APLICACION.clientes'),
        ),
        migrations.AddField(
            model_name='cita',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APLICACION.funcionarios'),
        ),
        migrations.AddField(
            model_name='cita',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lamascotaxd', to='APLICACION.clientes'),
        ),
        migrations.AddField(
            model_name='cita',
            name='tipoat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APLICACION.tipo_at'),
        ),
    ]
