# Generated by Django 4.1.2 on 2022-11-30 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APLICACION', '0006_rename_nombre_cli_clientes_nombre_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='nombre_masc',
            new_name='nombre_mascota',
        ),
    ]
