# Generated by Django 4.1.2 on 2022-11-30 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APLICACION', '0007_rename_nombre_masc_mascota_nombre_mascota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='rut_funcionario',
            new_name='rut_cliente',
        ),
        migrations.RenameField(
            model_name='funcionarios',
            old_name='nombre_fun',
            new_name='nombre_funcionario',
        ),
        migrations.RenameField(
            model_name='funcionarios',
            old_name='rut_f',
            new_name='rut_funcionario',
        ),
    ]
